import { generateWebsiteForBusiness } from '../_lib/website-pipeline.js';
import { hasWebsiteHtml } from '../_lib/website-config.js';

export const config = { maxDuration: 300 };

function cleanBusinessId(value) {
  var raw = String(value || '').trim();
  return /^\d+$/.test(raw) ? raw : '';
}

function buildPreviewUrl(websiteId) {
  return websiteId ? '/ver/' + encodeURIComponent(websiteId) : '';
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  var supabaseUrl = process.env.SUPABASE_URL;
  var serviceKey = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !serviceKey) {
    return res.status(503).json({ error: 'Supabase service key not configured' });
  }

  var body = req.body || {};
  var businessId = cleanBusinessId(body.businessId || body.business_id);
  if (!businessId) {
    return res.status(400).json({ error: 'businessId is required' });
  }

  var supabaseHeaders = {
    apikey: serviceKey,
    Authorization: 'Bearer ' + serviceKey,
    'Content-Type': 'application/json',
  };

  try {
    var businessRes = await fetch(
      supabaseUrl + '/rest/v1/businesses?id=eq.' + encodeURIComponent(businessId) + '&select=*',
      { headers: supabaseHeaders }
    );
    var businesses = businessRes.ok ? await businessRes.json() : [];
    if (!Array.isArray(businesses) || !businesses.length) {
      return res.status(404).json({ error: 'Business not found' });
    }

    var existingRes = await fetch(
      supabaseUrl + '/rest/v1/generated_websites?business_id=eq.' + encodeURIComponent(businessId) + '&select=id,published_url,config&order=created_at.desc&limit=5',
      { headers: supabaseHeaders }
    );
    var existingWebsites = existingRes.ok ? await existingRes.json() : [];
    var existing = Array.isArray(existingWebsites)
      ? existingWebsites.find(function (website) { return hasWebsiteHtml(website.config); })
      : null;

    if (existing) {
      return res.status(200).json({
        success: true,
        alreadyGenerated: true,
        websiteId: existing.id,
        publishedUrl: existing.published_url || null,
        previewUrl: existing.published_url || buildPreviewUrl(existing.id),
      });
    }

    var result = await generateWebsiteForBusiness(businesses[0], supabaseUrl, supabaseHeaders, { autoGenerated: true });

    await fetch(
      supabaseUrl + '/rest/v1/businesses?id=eq.' + encodeURIComponent(businessId),
      {
        method: 'PATCH',
        headers: { ...supabaseHeaders, Prefer: 'return=minimal' },
        body: JSON.stringify({
          pipeline_status: 'website_created',
          pipeline_status_changed_at: new Date().toISOString(),
        }),
      }
    ).catch(function (err) {
      console.warn('Failed to update business status after public demo generation:', err && err.message || err);
    });

    return res.status(200).json({
      success: true,
      websiteId: result.websiteId,
      publishedUrl: result.publishedUrl || null,
      previewUrl: result.publishedUrl || buildPreviewUrl(result.websiteId),
    });
  } catch (err) {
    console.error('public-builder/generate-demo error:', err);
    return res.status(500).json({ error: err.message || 'Website generation failed' });
  }
}
