export function getWebsiteHtml(config, options = {}) {
  const source = config && typeof config === 'object' ? config : {};
  const keys = options.preferDraft ? ['draft_html', 'html'] : ['html', 'draft_html'];

  for (const key of keys) {
    const value = source[key];
    if (typeof value === 'string' && value.trim()) {
      return value;
    }
  }

  return '';
}

export function hasWebsiteHtml(config) {
  return !!getWebsiteHtml(config);
}

export function buildWebsiteConfig({ existingConfig, researchReport, websiteContent, html, autoGenerated }) {
  const nextConfig = {
    ...(existingConfig && typeof existingConfig === 'object' ? existingConfig : {}),
    researchReport: researchReport || null,
    websiteContent: websiteContent || null,
    draft_html: html,
    html,
  };

  if (autoGenerated) {
    nextConfig.auto_generated = true;
  }

  return nextConfig;
}
