export function getWebsiteHtml(config, options = {}) {
  const source = config && typeof config === 'object' ? config : {};
  const keys = options.preferDraft ? ['draft_html', 'html'] : ['html', 'draft_html'];

  for (const key of keys) {
    const value = source[key];
    if (typeof value === 'string' && value.trim()) {
      return value;
    }
  }

  return '';
}

export function hasWebsiteHtml(config) {
  return !!getWebsiteHtml(config);
}

const RAW_WEBSITE_IMAGE_URL_PATTERN = /https?:\/\/[^\s"'()<>]+\/storage\/v1\/object\/public\/photos\/[^\s"'()<>]+\.(?:jpe?g|png)(?:\?[^\s"'()<>]*)?/ig;
const EXTERNAL_GOOGLE_IMAGE_URL_PATTERN = /https?:\/\/(?:lh3\.googleusercontent\.com|[^/\s"'()<>]*googleusercontent\.com)\/[^\s"'()<>]+/ig;

export function validateWebsiteHtmlImageSources(html) {
  const source = String(html || '');
  const rawStorageUrls = Array.from(new Set(source.match(RAW_WEBSITE_IMAGE_URL_PATTERN) || []));
  if (rawStorageUrls.length > 0) {
    throw new Error(`Website HTML contains raw non-WebP storage image URL(s): ${rawStorageUrls.slice(0, 3).join(', ')}`);
  }

  const googleUrls = Array.from(new Set(source.match(EXTERNAL_GOOGLE_IMAGE_URL_PATTERN) || []));
  if (googleUrls.length > 0) {
    throw new Error(`Website HTML contains external Google image URL(s): ${googleUrls.slice(0, 3).join(', ')}`);
  }
}

export function buildWebsiteConfig({ existingConfig, researchReport, websiteContent, photoManifest, html, autoGenerated }) {
  validateWebsiteHtmlImageSources(html);

  const previousConfig = existingConfig && typeof existingConfig === 'object' ? existingConfig : {};
  const nextConfig = {
    ...previousConfig,
    researchReport: researchReport || null,
    websiteContent: websiteContent || null,
    photoManifest: Array.isArray(photoManifest)
      ? photoManifest
      : (Array.isArray(previousConfig.photoManifest) ? previousConfig.photoManifest : []),
    draft_html: html,
    html,
  };

  if (autoGenerated) {
    nextConfig.auto_generated = true;
  }

  return nextConfig;
}
