-- ============================================================================
-- Local Business Finder — Supabase Database Schema
-- ============================================================================
-- Run this file in the Supabase SQL Editor to create all tables.
-- Source of truth for the data model. See CLAUDE.md for high-level overview.
-- ============================================================================

-- ============================================================================
-- 1. BUSINESSES — Core business record
-- ============================================================================
-- Central table for every discovered business. One row per Google Place ID.
-- Expanded to support the full Find → Gather → Curate → Generate pipeline.

CREATE TABLE IF NOT EXISTS businesses (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_code           TEXT UNIQUE NOT NULL DEFAULT 'BIZ-' || substr(md5(random()::text), 1, 6),
  place_id                TEXT UNIQUE NOT NULL,
  slug                    TEXT UNIQUE,              -- URL-safe slug for published website (e.g. "tacos-don-pepe")

  -- Identity
  name                    TEXT NOT NULL,
  description             TEXT,
  category                TEXT,                -- primary category: restaurant, salon, contractor, etc.
  subcategory             TEXT,                -- e.g., cuisine type, specialty

  -- Location
  address_full            TEXT,                -- full formatted address (from Google)
  address_street          TEXT,
  address_city            TEXT,
  address_state           TEXT,
  address_zip             TEXT,
  address_country         TEXT,
  latitude                DECIMAL(10, 7),
  longitude               DECIMAL(10, 7),
  service_area            TEXT,                -- for mobile/traveling businesses

  -- Contact
  phone                   TEXT,
  whatsapp                TEXT,
  email                   TEXT,
  website                 TEXT,                -- empty string = no website (our targets)

  -- Google Places data
  maps_url                TEXT,
  types                   TEXT[],              -- Google Places type tags
  rating                  DECIMAL(2, 1),       -- 0.0–5.0
  review_count            INTEGER DEFAULT 0,
  price_level             INTEGER,             -- 1–4 ($–$$$$)
  business_status         TEXT DEFAULT 'UNKNOWN'
                            CHECK (business_status IN (
                              'OPERATIONAL',
                              'CLOSED_TEMPORARILY',
                              'CLOSED_PERMANENTLY',
                              'UNKNOWN'
                            )),
  hours                   JSONB,               -- weekday descriptions array

  -- Business details (gathered from multiple sources)
  thumbnail               TEXT,                -- thumbnail image URL from search results
  service_options         TEXT[],              -- e.g., Dine-in, Takeout, Delivery
  amenities               TEXT[],              -- e.g., Wi-Fi, Parking, Outdoor seating
  highlights              TEXT[],              -- e.g., Great cocktails, Cozy atmosphere
  payment_methods         TEXT[],
  languages_spoken        TEXT[],
  accessibility_info      TEXT,
  parking_info            TEXT,
  year_established        INTEGER,
  owner_name              TEXT,

  -- Search context (how this business was discovered)
  search_location         TEXT,
  search_type             TEXT,

  -- Pipeline
  pipeline_status         TEXT DEFAULT 'saved'
                            CHECK (pipeline_status IN (
                              'saved', 'lead', 'demo', 'active_customer', 'inactive_customer'
                            )),
  contact_name            TEXT,                -- DEPRECATED: use business_contacts table. Kept for backward compat.
  contact_phone           TEXT,                -- DEPRECATED: use business_contacts table
  contact_email           TEXT,                -- DEPRECATED: use business_contacts table
  contact_whatsapp        TEXT,                -- DEPRECATED: use business_contacts table
  pipeline_status_changed_at TIMESTAMPTZ,
  outreach_sent           BOOLEAN DEFAULT FALSE,  -- true when all 6 core outreach steps complete
  outreach_steps          JSONB DEFAULT '{}',  -- per-step tracking: {"1":{"sent_at":"..."}, "2":{...}, ...}
  notes                   TEXT,                -- operator notes about the business

  -- Customer-authored content
  founder_description     TEXT,                -- founder story written by customer (100-300 chars)

  -- Tracking
  data_completeness_score INTEGER DEFAULT 0    -- 0–100, how much data we've gathered
                            CHECK (data_completeness_score BETWEEN 0 AND 100),
  first_discovered_at     TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW(),
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

-- Index for searching by location and category
CREATE INDEX IF NOT EXISTS idx_businesses_category ON businesses (category);
CREATE INDEX IF NOT EXISTS idx_businesses_city ON businesses (address_city);
CREATE INDEX IF NOT EXISTS idx_businesses_status ON businesses (business_status);
CREATE INDEX IF NOT EXISTS idx_businesses_completeness ON businesses (data_completeness_score);
CREATE INDEX IF NOT EXISTS idx_businesses_slug ON businesses (slug) WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_businesses_place_id ON businesses (place_id) WHERE place_id IS NOT NULL;

-- Composite: category + city search filter
CREATE INDEX IF NOT EXISTS idx_businesses_category_city ON businesses (category, address_city);

-- Functional: case-insensitive city filtering (used by get_audience_businesses RPC)
CREATE INDEX IF NOT EXISTS idx_businesses_city_lower ON businesses (LOWER(address_city));

-- Business code index for lookups
CREATE INDEX IF NOT EXISTS idx_businesses_code ON businesses (business_code);


-- ============================================================================
-- 1b. BUSINESS_CONTACTS — Multiple contacts per business
-- ============================================================================
-- Each business can have multiple contacts (e.g., cashier, manager, owner).
-- Contacts are people we interact with during the sales pipeline.

CREATE TABLE IF NOT EXISTS business_contacts (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_code            TEXT UNIQUE NOT NULL DEFAULT 'CON-' || substr(md5(random()::text), 1, 6),
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  contact_name            TEXT,
  contact_title           TEXT,                -- role/position: owner, manager, cashier, employee, etc.
  contact_phone           TEXT,
  contact_email           TEXT,
  contact_whatsapp        TEXT,
  notes                   TEXT,                -- notes about this specific contact
  is_primary              BOOLEAN DEFAULT FALSE,

  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_business_contacts_business_id ON business_contacts (business_id);
CREATE INDEX IF NOT EXISTS idx_business_contacts_code ON business_contacts (contact_code);


-- ============================================================================
-- 2. BUSINESS_SOCIAL_PROFILES — Social media & platform links
-- ============================================================================
-- One row per platform per business.
-- Stores links to Facebook, Instagram, WhatsApp, Yelp, delivery apps, etc.

CREATE TABLE IF NOT EXISTS business_social_profiles (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  platform                TEXT NOT NULL
                            CHECK (platform IN (
                              'facebook',
                              'instagram',
                              'whatsapp',
                              'twitter',
                              'tiktok',
                              'linkedin',
                              'youtube',
                              'yelp',
                              'tripadvisor',
                              'opentable',
                              'resy',
                              'doordash',
                              'ubereats',
                              'grubhub'
                            )),
  url                     TEXT,                -- full URL to the profile/page
  handle                  TEXT,                -- @handle or username (if applicable)
  follower_count          INTEGER,             -- number of followers on this platform
  post_count              INTEGER,             -- number of posts on this platform

  discovered_at           TIMESTAMPTZ DEFAULT NOW(),
  created_at              TIMESTAMPTZ DEFAULT NOW(),

  -- One profile per platform per business
  UNIQUE (business_id, platform)
);

CREATE INDEX IF NOT EXISTS idx_social_profiles_business ON business_social_profiles (business_id);


-- ============================================================================
-- 3. BUSINESS_PHOTOS — Photos from all sources
-- ============================================================================
-- Stores photo references from Google Places, social media, and AI generation.
-- Photos can be stored as URLs (external) or in Supabase Storage (persisted).

CREATE TABLE IF NOT EXISTS business_photos (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  source                  TEXT NOT NULL
                            CHECK (source IN (
                              'google',         -- from Google Places API / Google Business Profile
                              'facebook',
                              'instagram',
                              'yelp',
                              'tripadvisor',
                              'ai_generated',   -- created via NanoBanana or similar
                              'customer_upload'  -- uploaded by customer via data wizard
                            )),

  photo_type              TEXT
                            CHECK (photo_type IN (
                              'exterior',       -- outside of the business
                              'interior',       -- inside the business
                              'menu',           -- photo of a physical menu
                              'product',        -- product or service photo
                              'food',           -- food/drink items (restaurants)
                              'team',           -- staff or owner photos
                              'logo',           -- business logo
                              'founder',        -- founder/owner portrait (customer-uploaded)
                              'service',        -- photo of a specific service/product
                              'ai_generated'    -- AI-created supporting image
                            )),

  url                     TEXT,                -- original source URL
  storage_path            TEXT,                -- path in Supabase Storage bucket (for persisted copies)
  caption                 TEXT,
  is_primary              BOOLEAN DEFAULT FALSE, -- featured image for the business
  has_text_overlay        BOOLEAN DEFAULT NULL,  -- NULL = not scanned, TRUE = has promotional/decorative text
  width                   INTEGER,
  height                  INTEGER,

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_photos_business ON business_photos (business_id);
CREATE INDEX IF NOT EXISTS idx_photos_source ON business_photos (source);
CREATE INDEX IF NOT EXISTS idx_photos_type ON business_photos (photo_type);


-- ============================================================================
-- 4. BUSINESS_REVIEWS — Reviews from all platforms
-- ============================================================================
-- Reviews gathered from Google, Facebook, Yelp, TripAdvisor, etc.
-- Each review is scored with sentiment analysis and can be flagged for website use.

CREATE TABLE IF NOT EXISTS business_reviews (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  source                  TEXT NOT NULL
                            CHECK (source IN (
                              'google',
                              'facebook',
                              'yelp',
                              'tripadvisor',
                              'customer'         -- submitted by customer via data wizard
                            )),

  -- Review content
  author_name             TEXT,
  author_photo_url        TEXT,
  rating                  INTEGER CHECK (rating BETWEEN 1 AND 5),
  text                    TEXT,
  published_at            TEXT,                -- relative time from API (e.g., "2 weeks ago")

  -- Sentiment analysis
  sentiment_score         DECIMAL(5, 4),       -- raw score from analysis
  sentiment_label         TEXT
                            CHECK (sentiment_label IN (
                              'very_positive',
                              'positive',
                              'neutral',
                              'negative'
                            )),

  -- Curation
  is_curated              BOOLEAN DEFAULT FALSE, -- selected for use on generated website

  -- Deduplication: client-computed hash of (source + author_name + text)
  -- Used for upsert conflict detection, avoids index size issues with long text
  review_hash             TEXT,

  created_at              TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint for upsert: one review per hash per business
  UNIQUE (business_id, review_hash)
);

CREATE INDEX IF NOT EXISTS idx_reviews_business ON business_reviews (business_id);
CREATE INDEX IF NOT EXISTS idx_reviews_sentiment ON business_reviews (sentiment_label);
CREATE INDEX IF NOT EXISTS idx_reviews_curated ON business_reviews (is_curated) WHERE is_curated = TRUE;

-- Composite: curated reviews per business
CREATE INDEX IF NOT EXISTS idx_reviews_business_curated ON business_reviews (business_id, is_curated) WHERE is_curated = TRUE;

-- Composite: sentiment filtering per business
CREATE INDEX IF NOT EXISTS idx_reviews_business_sentiment ON business_reviews (business_id, sentiment_label);


-- ============================================================================
-- 5. BUSINESS_MENUS — Structured menu data
-- ============================================================================
-- Menu items extracted from photos (via OCR/AI) or gathered from online sources.
-- Primarily for restaurants but could apply to any service-based business.

CREATE TABLE IF NOT EXISTS business_menus (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  source_photo_id         UUID REFERENCES business_photos(id) ON DELETE SET NULL,

  menu_category           TEXT,                -- e.g., Appetizers, Entrees, Drinks, Desserts
  item_name               TEXT NOT NULL,
  item_description        TEXT,
  price                   DECIMAL(10, 2),
  currency                TEXT DEFAULT 'USD',  -- USD, MXN, COP, etc.

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_menus_business ON business_menus (business_id);


-- ============================================================================
-- 5b. BUSINESS_SERVICES — Customer-defined services/products
-- ============================================================================
-- Services or products the business offers, entered by the customer via the
-- data wizard. These are displayed on the generated website's services section
-- and complement the AI-written content with real data.

CREATE TABLE IF NOT EXISTS business_services (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  name                    TEXT NOT NULL,
  description             TEXT,
  price                   DECIMAL(10, 2),
  currency                TEXT DEFAULT 'MXN',  -- MXN, USD, COP, etc.
  photo_id                UUID REFERENCES business_photos(id) ON DELETE SET NULL,

  sort_order              INTEGER DEFAULT 0,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_services_business ON business_services (business_id);


-- ============================================================================
-- 6. GENERATED_WEBSITES — Website generation tracking
-- ============================================================================
-- One row per generation attempt. Tracks template, status, and selected content.

CREATE TABLE IF NOT EXISTS generated_websites (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  template_name           TEXT,                -- template used (mapped to business category)
  primary_color           TEXT,                -- hex color for branding
  secondary_color         TEXT,                -- hex color for accents
  status                  TEXT DEFAULT 'draft'
                            CHECK (status IN ('draft', 'published', 'archived')),
  site_status             TEXT DEFAULT NULL
                            CHECK (site_status IN ('active', 'suspended', 'archived')),
  published_url           TEXT,                -- live URL once deployed

  -- Custom domain support
  custom_domain           TEXT UNIQUE,         -- e.g. "www.tacosdonpepe.com"
  domain_status           TEXT DEFAULT NULL
                            CHECK (domain_status IN ('pending_verification', 'verified', 'failed')),
  domain_verified_at      TIMESTAMPTZ,

  -- Flexible config: selected photo IDs, review IDs, layout options, etc.
  config                  JSONB DEFAULT '{}',

  version                 INTEGER DEFAULT 1,   -- incremented on each re-publish
  last_edited_at          TIMESTAMPTZ,

  generated_at            TIMESTAMPTZ DEFAULT NOW(),
  published_at            TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_websites_business ON generated_websites (business_id);
CREATE INDEX IF NOT EXISTS idx_websites_status ON generated_websites (status);


-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
-- Enable RLS on all tables. Policies should be configured based on your
-- Supabase auth setup. Below enables RLS without restrictive policies
-- (open access via anon key, matching current app behavior).

ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_social_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_websites ENABLE ROW LEVEL SECURITY;

-- Open read/write policies for anon key (matches current app setup)
-- Replace these with proper auth policies when user authentication is added.

CREATE POLICY "Allow all access" ON businesses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON business_social_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON business_photos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON business_reviews FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON business_menus FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON generated_websites FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- UPDATED_AT TRIGGER
-- ============================================================================
-- Automatically updates last_updated_at on the businesses table when a row changes.

CREATE OR REPLACE FUNCTION update_last_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER businesses_updated_at
  BEFORE UPDATE ON businesses
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 7. WHATSAPP_CONVERSATIONS — One conversation per business
-- ============================================================================
-- Tracks 24-hour messaging window and unread state for the operator dashboard.

CREATE TABLE IF NOT EXISTS whatsapp_conversations (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT REFERENCES businesses(id) ON DELETE CASCADE,  -- nullable for unknown contacts
  recipient_phone         TEXT NOT NULL,            -- business owner's WhatsApp number (E.164)
  status                  TEXT DEFAULT 'active'
                            CHECK (status IN ('active', 'archived')),
  last_inbound_at         TIMESTAMPTZ,             -- tracks 24-hour messaging window
  unread_count            INTEGER DEFAULT 0,        -- denormalized for fast list display
  auto_reply_disabled     BOOLEAN DEFAULT FALSE,    -- operator toggle to suppress auto-replies
  last_message_text       TEXT,                     -- preview for conversations list
  last_message_at         TIMESTAMPTZ,             -- sort conversations by recency
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW(),

  -- One conversation per phone number
  UNIQUE (recipient_phone)
);

CREATE INDEX IF NOT EXISTS idx_wa_conv_business ON whatsapp_conversations (business_id);
CREATE INDEX IF NOT EXISTS idx_wa_conv_last_msg ON whatsapp_conversations (last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_wa_conv_unread ON whatsapp_conversations (unread_count) WHERE unread_count > 0;

CREATE TRIGGER whatsapp_conversations_updated_at
  BEFORE UPDATE ON whatsapp_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 8. WHATSAPP_MESSAGES — Individual messages (both directions)
-- ============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_messages (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id         UUID NOT NULL REFERENCES whatsapp_conversations(id) ON DELETE CASCADE,
  business_id             BIGINT REFERENCES businesses(id) ON DELETE CASCADE,  -- nullable for unknown contacts
  direction               TEXT NOT NULL
                            CHECK (direction IN ('outbound', 'inbound')),
  message_type            TEXT DEFAULT 'text'
                            CHECK (message_type IN ('text', 'template', 'image', 'document')),
  body                    TEXT,                     -- message content
  template_name           TEXT,                     -- WhatsApp template name (if template msg)
  template_params         JSONB,                    -- template parameter values
  wamid                   TEXT UNIQUE,              -- WhatsApp Message ID from Meta
  status                  TEXT DEFAULT 'pending'
                            CHECK (status IN ('pending', 'sent', 'delivered', 'read', 'failed')),
  error_message           TEXT,                     -- error details if failed
  sent_at                 TIMESTAMPTZ,
  delivered_at            TIMESTAMPTZ,
  read_at                 TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wa_msg_conv ON whatsapp_messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_wa_msg_business ON whatsapp_messages (business_id);
CREATE INDEX IF NOT EXISTS idx_wa_msg_wamid ON whatsapp_messages (wamid);
CREATE INDEX IF NOT EXISTS idx_wa_msg_status ON whatsapp_messages (status) WHERE status NOT IN ('delivered', 'read');

-- Composite: recent messages per business
CREATE INDEX IF NOT EXISTS idx_wa_msg_business_created ON whatsapp_messages (business_id, created_at DESC);


-- ============================================================================
-- 9. WHATSAPP_TEMPLATES — Cached Meta-approved message templates
-- ============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_templates (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  template_name           TEXT UNIQUE NOT NULL,      -- Meta template name
  language                TEXT DEFAULT 'en',
  category                TEXT,                      -- MARKETING / UTILITY / AUTHENTICATION
  body_text               TEXT,                      -- body with {{1}}, {{2}} placeholders
  header_text             TEXT,
  footer_text             TEXT,
  param_count             INTEGER DEFAULT 0,         -- number of parameters
  meta_status             TEXT DEFAULT 'PENDING'
                            CHECK (meta_status IN ('APPROVED', 'PENDING', 'REJECTED')),
  last_synced_at          TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- WHATSAPP RLS POLICIES
-- ============================================================================

ALTER TABLE whatsapp_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access" ON whatsapp_conversations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON whatsapp_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON whatsapp_templates FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 10. MARKETING_LEADS — Lead capture from marketing website
-- ============================================================================
-- Stores leads submitted via the marketing landing page "create free page" form.

CREATE TABLE IF NOT EXISTS marketing_leads (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_name           TEXT NOT NULL,
  facebook_url            TEXT,
  google_listing_url      TEXT,
  name                    TEXT,
  phone                   TEXT,
  email                   TEXT,
  city                    TEXT,
  address                 TEXT,                -- full address for Google Places matching
  source                  TEXT DEFAULT 'website',
  status                  TEXT DEFAULT 'new'
                            CHECK (status IN ('new', 'contacted', 'qualified', 'converted', 'lost')),
  notes                   TEXT,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_marketing_leads_status ON marketing_leads (status);
CREATE INDEX IF NOT EXISTS idx_marketing_leads_created ON marketing_leads (created_at DESC);

ALTER TABLE marketing_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON marketing_leads FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 10b. WHATSAPP_AUDIENCES — Named audience segments for campaign targeting
-- ============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_audiences (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name                TEXT NOT NULL,
  description         TEXT,
  filters             JSONB NOT NULL DEFAULT '{}',
  business_count      INTEGER DEFAULT 0,
  last_computed_at    TIMESTAMPTZ,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wa_audiences_name ON whatsapp_audiences (name);

ALTER TABLE whatsapp_audiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON whatsapp_audiences FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER whatsapp_audiences_updated_at
  BEFORE UPDATE ON whatsapp_audiences FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 10c. WHATSAPP_CAMPAIGNS — Bulk message campaigns
-- ============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_campaigns (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name                TEXT NOT NULL,
  audience_id         UUID NOT NULL REFERENCES whatsapp_audiences(id) ON DELETE RESTRICT,
  template_id         UUID NOT NULL REFERENCES whatsapp_templates(id) ON DELETE RESTRICT,
  template_params     JSONB DEFAULT '[]',
  status              TEXT DEFAULT 'draft'
                        CHECK (status IN ('draft', 'scheduled', 'sending', 'sent', 'cancelled', 'failed')),
  scheduled_at        TIMESTAMPTZ,
  started_at          TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ,
  send_offset         INTEGER DEFAULT 0,
  total_recipients    INTEGER DEFAULT 0,
  sent_count          INTEGER DEFAULT 0,
  delivered_count     INTEGER DEFAULT 0,
  read_count          INTEGER DEFAULT 0,
  replied_count       INTEGER DEFAULT 0,
  failed_count        INTEGER DEFAULT 0,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wa_campaigns_status ON whatsapp_campaigns (status);
CREATE INDEX IF NOT EXISTS idx_wa_campaigns_audience ON whatsapp_campaigns (audience_id);

ALTER TABLE whatsapp_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON whatsapp_campaigns FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER whatsapp_campaigns_updated_at
  BEFORE UPDATE ON whatsapp_campaigns FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 10d. WHATSAPP_CAMPAIGN_MESSAGES — Links campaigns to individual messages
-- ============================================================================

CREATE TABLE IF NOT EXISTS whatsapp_campaign_messages (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  campaign_id     UUID NOT NULL REFERENCES whatsapp_campaigns(id) ON DELETE CASCADE,
  message_id      UUID NOT NULL REFERENCES whatsapp_messages(id) ON DELETE CASCADE,
  business_id     BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (campaign_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_wa_campaign_msgs_campaign ON whatsapp_campaign_messages (campaign_id);
CREATE INDEX IF NOT EXISTS idx_wa_campaign_msgs_business ON whatsapp_campaign_messages (business_id);

ALTER TABLE whatsapp_campaign_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON whatsapp_campaign_messages FOR ALL USING (true) WITH CHECK (true);


-- Add campaign_id to whatsapp_messages for fast filtering
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS campaign_id UUID REFERENCES whatsapp_campaigns(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_wa_msg_campaign ON whatsapp_messages (campaign_id) WHERE campaign_id IS NOT NULL;


-- ============================================================================
-- RPC: get_audience_businesses — resolve audience filters to business list
-- ============================================================================

CREATE OR REPLACE FUNCTION get_audience_businesses(p_filters JSONB, p_limit INT DEFAULT 100, p_offset INT DEFAULT 0)
RETURNS TABLE (
  business_id BIGINT,
  name TEXT,
  phone TEXT,
  address_city TEXT,
  address_country TEXT,
  category TEXT,
  rating DECIMAL,
  messages_sent BIGINT,
  replies_received BIGINT,
  last_contacted_at TIMESTAMPTZ,
  total_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  WITH business_stats AS (
    SELECT
      b.id,
      b.name,
      b.phone,
      b.address_city,
      b.address_country,
      b.category,
      b.rating,
      COALESCE(ms.sent_count, 0) AS messages_sent,
      COALESCE(ms.reply_count, 0) AS replies_received,
      ms.last_sent AS last_contacted_at
    FROM businesses b
    LEFT JOIN (
      SELECT
        wm.business_id,
        COUNT(*) FILTER (WHERE wm.direction = 'outbound') AS sent_count,
        COUNT(*) FILTER (WHERE wm.direction = 'inbound') AS reply_count,
        MAX(wm.created_at) FILTER (WHERE wm.direction = 'outbound') AS last_sent
      FROM whatsapp_messages wm
      GROUP BY wm.business_id
    ) ms ON ms.business_id = b.id
    WHERE
      b.phone IS NOT NULL AND b.phone != ''
      AND (p_filters->>'address_city' IS NULL OR b.address_city ILIKE '%' || (p_filters->>'address_city') || '%')
      AND (p_filters->>'address_state' IS NULL OR b.address_state ILIKE '%' || (p_filters->>'address_state') || '%')
      AND (p_filters->>'address_country' IS NULL OR b.address_country = p_filters->>'address_country')
      AND (p_filters->>'category' IS NULL OR b.category ILIKE '%' || (p_filters->>'category') || '%')
      AND (p_filters->>'rating_min' IS NULL OR b.rating >= (p_filters->>'rating_min')::DECIMAL)
      AND (p_filters->>'rating_max' IS NULL OR b.rating <= (p_filters->>'rating_max')::DECIMAL)
      AND (p_filters->>'messages_sent_min' IS NULL OR COALESCE(ms.sent_count, 0) >= (p_filters->>'messages_sent_min')::INT)
      AND (p_filters->>'messages_sent_max' IS NULL OR COALESCE(ms.sent_count, 0) <= (p_filters->>'messages_sent_max')::INT)
      AND (p_filters->>'replies_min' IS NULL OR COALESCE(ms.reply_count, 0) >= (p_filters->>'replies_min')::INT)
      AND (p_filters->>'replies_max' IS NULL OR COALESCE(ms.reply_count, 0) <= (p_filters->>'replies_max')::INT)
      AND (p_filters->>'last_contacted_after' IS NULL OR ms.last_sent >= (p_filters->>'last_contacted_after')::TIMESTAMPTZ)
      AND (p_filters->>'last_contacted_before' IS NULL OR ms.last_sent <= (p_filters->>'last_contacted_before')::TIMESTAMPTZ)
      AND (p_filters->>'never_contacted' IS NULL OR (p_filters->>'never_contacted')::BOOLEAN = FALSE OR ms.last_sent IS NULL)
  )
  SELECT
    bs.id AS business_id,
    bs.name,
    bs.phone,
    bs.address_city,
    bs.address_country,
    bs.category,
    bs.rating,
    bs.messages_sent,
    bs.replies_received,
    bs.last_contacted_at,
    COUNT(*) OVER () AS total_count
  FROM business_stats bs
  ORDER BY bs.name
  LIMIT p_limit
  OFFSET p_offset;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- RPC: count_audience_businesses — lightweight count-only version
-- ============================================================================
-- Returns just the count of matching businesses. No window functions, no
-- ordering, no pagination overhead. Used by audience create/update to get
-- the business_count without the full query cost.

CREATE OR REPLACE FUNCTION count_audience_businesses(p_filters JSONB)
RETURNS BIGINT AS $$
DECLARE
  result BIGINT;
BEGIN
  SELECT COUNT(*)
  INTO result
  FROM businesses b
  LEFT JOIN (
    SELECT
      wm.business_id,
      COUNT(*) FILTER (WHERE wm.direction = 'outbound') AS sent_count,
      COUNT(*) FILTER (WHERE wm.direction = 'inbound') AS reply_count,
      MAX(wm.created_at) FILTER (WHERE wm.direction = 'outbound') AS last_sent
    FROM whatsapp_messages wm
    GROUP BY wm.business_id
  ) ms ON ms.business_id = b.id
  WHERE
    b.phone IS NOT NULL AND b.phone != ''
    AND (p_filters->>'address_city' IS NULL OR b.address_city ILIKE '%' || (p_filters->>'address_city') || '%')
    AND (p_filters->>'address_state' IS NULL OR b.address_state ILIKE '%' || (p_filters->>'address_state') || '%')
    AND (p_filters->>'address_country' IS NULL OR b.address_country = p_filters->>'address_country')
    AND (p_filters->>'category' IS NULL OR b.category ILIKE '%' || (p_filters->>'category') || '%')
    AND (p_filters->>'rating_min' IS NULL OR b.rating >= (p_filters->>'rating_min')::DECIMAL)
    AND (p_filters->>'rating_max' IS NULL OR b.rating <= (p_filters->>'rating_max')::DECIMAL)
    AND (p_filters->>'messages_sent_min' IS NULL OR COALESCE(ms.sent_count, 0) >= (p_filters->>'messages_sent_min')::INT)
    AND (p_filters->>'messages_sent_max' IS NULL OR COALESCE(ms.sent_count, 0) <= (p_filters->>'messages_sent_max')::INT)
    AND (p_filters->>'replies_min' IS NULL OR COALESCE(ms.reply_count, 0) >= (p_filters->>'replies_min')::INT)
    AND (p_filters->>'replies_max' IS NULL OR COALESCE(ms.reply_count, 0) <= (p_filters->>'replies_max')::INT)
    AND (p_filters->>'last_contacted_after' IS NULL OR ms.last_sent >= (p_filters->>'last_contacted_after')::TIMESTAMPTZ)
    AND (p_filters->>'last_contacted_before' IS NULL OR ms.last_sent <= (p_filters->>'last_contacted_before')::TIMESTAMPTZ)
    AND (p_filters->>'never_contacted' IS NULL OR (p_filters->>'never_contacted')::BOOLEAN = FALSE OR ms.last_sent IS NULL);

  RETURN result;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- 11. PRODUCTS — Subscription products and pricing
-- ============================================================================
-- Defines the products available for purchase. Links to Stripe Product + Price.

CREATE TABLE IF NOT EXISTS products (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name                    TEXT NOT NULL,
  description             TEXT,
  price                   DECIMAL(10, 2) NOT NULL,
  currency                TEXT DEFAULT 'MXN'
                            CHECK (currency IN ('MXN', 'USD', 'COP')),
  billing_interval        TEXT DEFAULT 'monthly'
                            CHECK (billing_interval IN ('monthly', 'yearly', 'one_time')),
  features                JSONB DEFAULT '[]',          -- array of strings (bullet points for checkout)
  stripe_product_id       TEXT,
  stripe_price_id         TEXT,
  commission_amount       DECIMAL(10, 2) DEFAULT 100.00,  -- commission per active subscription (MXN)
  is_active               BOOLEAN DEFAULT TRUE,
  sort_order              INTEGER DEFAULT 0,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_active ON products (is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_products_sort ON products (sort_order);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON products FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 12. CUSTOMERS — Business-to-customer relationship
-- ============================================================================
-- Created when a prospect converts to a paying customer via Stripe Checkout.

CREATE TABLE IF NOT EXISTS customers (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  stripe_customer_id      TEXT UNIQUE,               -- Stripe Customer ID
  email                   TEXT NOT NULL,              -- customer email (for auth + billing)
  contact_name            TEXT,                       -- business owner name
  monthly_price           DECIMAL(10, 2),             -- subscription price
  currency                TEXT DEFAULT 'USD',         -- USD, MXN, COP, etc.
  notes                   TEXT,                       -- operator notes
  referral_source         TEXT,                       -- how the customer heard about us (collected via WhatsApp)
  sales_rep_employee_id   UUID REFERENCES employees(id) ON DELETE SET NULL,  -- employee who sourced this sale
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customers_business ON customers (business_id);
CREATE INDEX IF NOT EXISTS idx_customers_stripe ON customers (stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);
CREATE INDEX IF NOT EXISTS idx_customers_sales_rep ON customers (sales_rep_employee_id) WHERE sales_rep_employee_id IS NOT NULL;

CREATE TRIGGER customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 12. SUBSCRIPTIONS — Stripe subscription records
-- ============================================================================
-- Synced via Stripe webhooks. One active subscription per customer.

CREATE TABLE IF NOT EXISTS subscriptions (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id             UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  stripe_subscription_id  TEXT UNIQUE,               -- Stripe Subscription ID
  stripe_price_id         TEXT,                      -- Stripe Price ID
  status                  TEXT DEFAULT 'incomplete'
                            CHECK (status IN ('active', 'past_due', 'cancelled', 'incomplete', 'trialing')),
  current_period_start    TIMESTAMPTZ,
  current_period_end      TIMESTAMPTZ,
  cancel_at_period_end    BOOLEAN DEFAULT FALSE,
  cancelled_at            TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_customer ON subscriptions (customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe ON subscriptions (stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions (status);


-- ============================================================================
-- 13. CUSTOMER_USERS — Links Supabase Auth users to customer records
-- ============================================================================
-- Enables RLS: each authenticated user can only access their own customer data.

CREATE TABLE IF NOT EXISTS customer_users (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  auth_user_id            UUID NOT NULL UNIQUE,      -- Supabase Auth user UUID
  customer_id             UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  role                    TEXT DEFAULT 'owner'
                            CHECK (role IN ('owner', 'manager', 'employee')),
  display_name            TEXT,
  email                   TEXT,
  is_active               BOOLEAN DEFAULT TRUE,
  invited_at              TIMESTAMPTZ,
  joined_at               TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customer_users_auth ON customer_users (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_customer_users_customer ON customer_users (customer_id);


-- ============================================================================
-- 14. EDIT_REQUESTS — Customer website change requests
-- ============================================================================
-- Submitted by customers via the admin portal. Managed by operators.

CREATE TABLE IF NOT EXISTS edit_requests (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  customer_id             UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  website_id              UUID REFERENCES generated_websites(id) ON DELETE SET NULL,
  request_type            TEXT NOT NULL
                            CHECK (request_type IN (
                              'content_update', 'photo_update', 'contact_update',
                              'hours_update', 'menu_update', 'design_change', 'other'
                            )),
  description             TEXT NOT NULL,
  status                  TEXT DEFAULT 'submitted'
                            CHECK (status IN ('submitted', 'processing', 'in_review', 'in_progress', 'ready_for_review', 'completed', 'rejected', 'customer_rejected')),
  priority                TEXT DEFAULT 'normal'
                            CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  rejection_reason        TEXT,
  ai_edit_summary         TEXT,                        -- AI-generated summary of what was changed in the HTML
  element_type            TEXT,                        -- visual editor: type of element (text, image, heading, button, section)
  element_selector        TEXT,                        -- visual editor: CSS selector path to the element
  element_screenshot_url  TEXT,                        -- visual editor: screenshot URL of the clicked element
  current_value           TEXT,                        -- visual editor: current text/src/content of the element
  ai_conversation         JSONB,                       -- visual editor: full AI chat conversation array
  admin_notes             TEXT,                        -- internal notes from admin when processing
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_edit_requests_customer ON edit_requests (customer_id);
CREATE INDEX IF NOT EXISTS idx_edit_requests_business ON edit_requests (business_id);
CREATE INDEX IF NOT EXISTS idx_edit_requests_status ON edit_requests (status);

CREATE TRIGGER edit_requests_updated_at
  BEFORE UPDATE ON edit_requests
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 16. EMPLOYEES — Internal team members with app access
-- ============================================================================
-- Links Supabase Auth users to employee roles. Used for login gating and
-- future per-employee lead tracking.

CREATE TABLE IF NOT EXISTS employees (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  auth_user_id            UUID NOT NULL UNIQUE,      -- Supabase Auth user UUID
  email                   TEXT NOT NULL,              -- denormalized for display
  display_name            TEXT,
  outreach_sender_name    TEXT,                    -- name used in WhatsApp outreach messages
  tracking_code           TEXT UNIQUE,             -- unique code for sales attribution links
  role                    TEXT DEFAULT 'employee'
                            CHECK (role IN ('admin', 'employee')),
  is_active               BOOLEAN DEFAULT TRUE,
  invited_at              TIMESTAMPTZ,
  joined_at               TIMESTAMPTZ,
  welcome_email_sent_at   TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employees_auth ON employees (auth_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_email ON employees (email);
CREATE INDEX IF NOT EXISTS idx_employees_active ON employees (is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_employees_tracking_code ON employees (tracking_code) WHERE tracking_code IS NOT NULL;

CREATE TRIGGER employees_updated_at
  BEFORE UPDATE ON employees
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON employees FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 17. EMPLOYEE_APPLICATIONS — Prospective employee applications
-- ============================================================================
-- Public-facing application form submissions. No auth required to insert.
-- Reviewed by admin employees.

CREATE TABLE IF NOT EXISTS employee_applications (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name                    TEXT NOT NULL,
  email                   TEXT NOT NULL,
  phone                   TEXT,
  message                 TEXT,
  status                  TEXT DEFAULT 'pending'
                            CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by             UUID REFERENCES employees(id) ON DELETE SET NULL,
  reviewed_at             TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employee_applications_status ON employee_applications (status);
CREATE INDEX IF NOT EXISTS idx_employee_applications_email ON employee_applications (email);

ALTER TABLE employee_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON employee_applications FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- CUSTOMER PORTAL RLS POLICIES
-- ============================================================================
-- Open policies for operator access. Customer-scoped policies use auth.uid().

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE edit_requests ENABLE ROW LEVEL SECURITY;

-- Operator (anon key) open access
CREATE POLICY "Allow all access" ON customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON subscriptions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON customer_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON edit_requests FOR ALL USING (true) WITH CHECK (true);

-- Customer-scoped read policies (for authenticated users via Supabase Auth)
-- These allow customers to read only their own data when using the auth token.
-- The "Allow all access" policies above take precedence for anon key (operator).

CREATE POLICY "Customers read own data" ON customers
  FOR SELECT USING (
    id IN (SELECT customer_id FROM customer_users WHERE auth_user_id = auth.uid())
  );

CREATE POLICY "Customers read own subscriptions" ON subscriptions
  FOR SELECT USING (
    customer_id IN (SELECT customer_id FROM customer_users WHERE auth_user_id = auth.uid())
  );

CREATE POLICY "Customers read own user record" ON customer_users
  FOR SELECT USING (auth_user_id = auth.uid());

CREATE POLICY "Customers read own team" ON customer_users
  FOR SELECT USING (
    customer_id IN (SELECT customer_id FROM customer_users WHERE auth_user_id = auth.uid())
  );

CREATE POLICY "Customers read own edit requests" ON edit_requests
  FOR SELECT USING (
    customer_id IN (SELECT customer_id FROM customer_users WHERE auth_user_id = auth.uid())
  );

CREATE POLICY "Customers insert edit requests" ON edit_requests
  FOR INSERT WITH CHECK (
    customer_id IN (SELECT customer_id FROM customer_users WHERE auth_user_id = auth.uid())
  );


-- ============================================================================
-- 17. EMAIL_CONVERSATIONS — One per unique sender email
-- ============================================================================
-- Mirrors whatsapp_conversations. Groups email threads by sender address.

CREATE TABLE IF NOT EXISTS email_conversations (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_email            TEXT NOT NULL UNIQUE,           -- unique sender address
  sender_name             TEXT,                           -- display name from email header
  customer_id             UUID REFERENCES customers(id) ON DELETE SET NULL,
  business_id             BIGINT REFERENCES businesses(id) ON DELETE SET NULL,
  unread_count            INTEGER DEFAULT 0,
  last_message_subject    TEXT,
  last_message_text       TEXT,                           -- plain-text preview (first 200 chars)
  last_message_at         TIMESTAMPTZ,
  status                  TEXT DEFAULT 'active'
                            CHECK (status IN ('active', 'archived')),
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_conversations_customer ON email_conversations (customer_id);
CREATE INDEX IF NOT EXISTS idx_email_conversations_business ON email_conversations (business_id);
CREATE INDEX IF NOT EXISTS idx_email_conversations_last_msg ON email_conversations (last_message_at DESC);

ALTER TABLE email_conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON email_conversations FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER email_conversations_updated_at
  BEFORE UPDATE ON email_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 18. EMAIL_MESSAGES — Individual email messages in both directions
-- ============================================================================
-- Mirrors whatsapp_messages. Stores inbound and outbound emails.

CREATE TABLE IF NOT EXISTS email_messages (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id         UUID NOT NULL REFERENCES email_conversations(id) ON DELETE CASCADE,
  resend_email_id         TEXT,                           -- Resend email ID (from webhook or send response)
  direction               TEXT NOT NULL
                            CHECK (direction IN ('inbound', 'outbound')),
  from_address            TEXT,
  to_addresses            TEXT[],                         -- array of recipient addresses
  cc_addresses            TEXT[],                         -- array of CC addresses
  subject                 TEXT,
  body_html               TEXT,
  body_text               TEXT,
  has_attachments         BOOLEAN DEFAULT FALSE,
  attachment_metadata     JSONB,                          -- array of { filename, content_type, size }
  status                  TEXT DEFAULT 'received'
                            CHECK (status IN ('received', 'sent', 'failed')),
  sent_at                 TIMESTAMPTZ,
  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_messages_conversation ON email_messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_resend_id ON email_messages (resend_email_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_created ON email_messages (created_at);

ALTER TABLE email_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON email_messages FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 19. EMAIL_TEMPLATES — Editable email templates for transactional/marketing emails
-- ============================================================================
-- Stores email templates created via the drag-and-drop editor (GrapesJS).
-- Templates with a trigger_key are used for automated transactional emails.
-- Falls back to hardcoded templates in email-templates.js if no stored template exists.

CREATE TABLE IF NOT EXISTS email_templates (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name                    TEXT NOT NULL,
  description             TEXT,
  category                TEXT NOT NULL DEFAULT 'custom'
                            CHECK (category IN ('transactional', 'marketing', 'custom')),
  trigger_key             TEXT UNIQUE,              -- links to automation events (e.g. 'customer_welcome')
  subject                 TEXT NOT NULL,
  body_html               TEXT NOT NULL,
  body_text               TEXT,
  gjs_components          JSONB,                    -- GrapesJS editor state (components JSON)
  gjs_styles              JSONB,                    -- GrapesJS editor state (styles JSON)
  gjs_html                TEXT,                     -- GrapesJS raw HTML output
  merge_tags              TEXT[],                   -- available merge tag names for this template
  is_active               BOOLEAN DEFAULT TRUE,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_templates_category ON email_templates (category);
CREATE INDEX IF NOT EXISTS idx_email_templates_trigger_key ON email_templates (trigger_key);
CREATE INDEX IF NOT EXISTS idx_email_templates_active ON email_templates (is_active);

ALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON email_templates FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 20. ANALYTICS_EVENTS — Raw website visitor tracking events
-- ============================================================================
-- First-party analytics from the tracking script injected into published websites.
-- Privacy-first: no cookies, no PII, visitor_id is a hashed fingerprint.

CREATE TABLE IF NOT EXISTS analytics_events (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  website_id              UUID REFERENCES generated_websites(id) ON DELETE SET NULL,

  event_type              TEXT NOT NULL
                            CHECK (event_type IN (
                              'page_view',
                              'click_phone',
                              'click_email',
                              'click_directions',
                              'click_social',
                              'form_submit',
                              'demo_view',
                              'demo_leave'
                            )),
  page_url                TEXT,
  referrer                TEXT,                -- domain only, not full URL
  device_type             TEXT
                            CHECK (device_type IN ('desktop', 'mobile', 'tablet')),
  visitor_id              TEXT,                -- hashed fingerprint for unique visitor counting (no PII)
  metadata                JSONB DEFAULT '{}',

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_business_id ON analytics_events (business_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_business_date ON analytics_events (business_id, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_type ON analytics_events (event_type);


-- ============================================================================
-- 21. ANALYTICS_SUMMARIES — Daily pre-aggregated metrics
-- ============================================================================
-- Rolled up daily by a Vercel Cron job for fast dashboard queries.

CREATE TABLE IF NOT EXISTS analytics_summaries (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  date                    DATE NOT NULL,

  page_views              INTEGER DEFAULT 0,
  unique_visitors         INTEGER DEFAULT 0,
  phone_clicks            INTEGER DEFAULT 0,
  email_clicks            INTEGER DEFAULT 0,
  direction_clicks        INTEGER DEFAULT 0,
  social_clicks           INTEGER DEFAULT 0,
  form_submissions        INTEGER DEFAULT 0,

  top_referrers           JSONB DEFAULT '{}',
  device_breakdown        JSONB DEFAULT '{}',

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_analytics_summaries_unique ON analytics_summaries (business_id, date);
CREATE INDEX IF NOT EXISTS idx_analytics_summaries_business_date ON analytics_summaries (business_id, date);


-- ============================================================================
-- 22. REFERRAL_CODES — One referral code per customer
-- ============================================================================
-- Short, human-readable codes customers share to refer other businesses.

CREATE TABLE IF NOT EXISTS referral_codes (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id             UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  code                    TEXT UNIQUE NOT NULL,        -- short code like "TACOS42"
  is_active               BOOLEAN DEFAULT TRUE,
  total_referrals         INTEGER DEFAULT 0,           -- denormalized count
  successful_referrals    INTEGER DEFAULT 0,           -- converted count
  total_rewards           INTEGER DEFAULT 0,           -- free months earned
  created_at              TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (customer_id)                                  -- one code per customer
);

CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON referral_codes (code);
CREATE INDEX IF NOT EXISTS idx_referral_codes_customer ON referral_codes (customer_id);

ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON referral_codes FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 23. REFERRALS — Individual referral tracking
-- ============================================================================
-- Tracks each referral from creation through conversion and reward application.

CREATE TABLE IF NOT EXISTS referrals (
  id                      UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  referral_code_id        UUID NOT NULL REFERENCES referral_codes(id) ON DELETE CASCADE,
  referrer_customer_id    UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,

  -- Referred business info (captured at landing page)
  referred_business_name  TEXT,
  referred_phone          TEXT,
  referred_email          TEXT,
  referred_city           TEXT,

  -- Tracking (set when they convert to a customer)
  referred_customer_id    UUID REFERENCES customers(id) ON DELETE SET NULL,
  referred_business_id    BIGINT REFERENCES businesses(id) ON DELETE SET NULL,

  -- Status lifecycle
  status                  TEXT DEFAULT 'pending'
                            CHECK (status IN (
                              'pending',          -- lead captured, not yet converted
                              'contacted',        -- we reached out
                              'converted',        -- they became a customer
                              'rewarded',         -- both rewards applied
                              'expired',          -- no conversion after 90 days
                              'rejected'          -- invalid or spam
                            )),

  -- Rewards
  referrer_reward_status  TEXT DEFAULT 'pending'
                            CHECK (referrer_reward_status IN ('pending', 'applied', 'not_eligible')),
  referrer_stripe_credit_id TEXT,                  -- Stripe balance transaction ID for the free month
  referred_reward_status  TEXT DEFAULT 'pending'
                            CHECK (referred_reward_status IN ('pending', 'applied', 'not_eligible')),
  referred_stripe_coupon_id TEXT,                  -- Stripe coupon ID applied to referred subscription

  -- Source tracking
  source                  TEXT DEFAULT 'whatsapp'
                            CHECK (source IN ('whatsapp', 'link', 'manual')),

  created_at              TIMESTAMPTZ DEFAULT NOW(),
  converted_at            TIMESTAMPTZ,
  rewarded_at             TIMESTAMPTZ,
  last_updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_referrals_code ON referrals (referral_code_id);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals (referrer_customer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_status ON referrals (status);

ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON referrals FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER referrals_updated_at
  BEFORE UPDATE ON referrals FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 24. MARKETING_LEADS — Referral columns
-- ============================================================================
-- Links marketing leads captured via referral back to the referral record.

ALTER TABLE marketing_leads ADD COLUMN IF NOT EXISTS referral_code TEXT;
ALTER TABLE marketing_leads ADD COLUMN IF NOT EXISTS referral_id UUID REFERENCES referrals(id) ON DELETE SET NULL;


-- ============================================================================
-- 25. SCHEDULING — Column additions to businesses
-- ============================================================================

ALTER TABLE businesses ADD COLUMN IF NOT EXISTS scheduling_type TEXT
  CHECK (scheduling_type IN ('appointment_based', 'class_based'));

ALTER TABLE businesses ADD COLUMN IF NOT EXISTS scheduling_config JSONB DEFAULT '{}';


-- ============================================================================
-- 26. STAFF_MEMBERS — Staff/employees of the business (instructors, barbers)
-- ============================================================================

CREATE TABLE IF NOT EXISTS staff_members (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  phone             TEXT,
  email             TEXT,
  photo_url         TEXT,
  bio               TEXT,
  specialties       TEXT[] DEFAULT '{}',
  is_active         BOOLEAN DEFAULT TRUE,
  sort_order        INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_staff_members_business ON staff_members (business_id);
CREATE INDEX IF NOT EXISTS idx_staff_members_active ON staff_members (business_id, is_active) WHERE is_active = TRUE;

ALTER TABLE staff_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON staff_members FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER staff_members_updated_at
  BEFORE UPDATE ON staff_members
  FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 27. STAFF_SCHEDULES — Recurring weekly availability per staff member
-- ============================================================================

CREATE TABLE IF NOT EXISTS staff_schedules (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  staff_member_id   UUID NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  day_of_week       INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time        TIME NOT NULL,
  end_time          TIME NOT NULL,
  is_active         BOOLEAN DEFAULT TRUE,
  created_at        TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (staff_member_id, day_of_week, start_time)
);

CREATE INDEX IF NOT EXISTS idx_staff_schedules_staff ON staff_schedules (staff_member_id);
CREATE INDEX IF NOT EXISTS idx_staff_schedules_business ON staff_schedules (business_id);

ALTER TABLE staff_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON staff_schedules FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 28. STAFF_EXCEPTIONS — Days off, holidays, custom hours
-- ============================================================================

CREATE TABLE IF NOT EXISTS staff_exceptions (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  staff_member_id   UUID NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  exception_date    DATE NOT NULL,
  is_available      BOOLEAN DEFAULT FALSE,
  start_time        TIME,
  end_time          TIME,
  reason            TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (staff_member_id, exception_date)
);

CREATE INDEX IF NOT EXISTS idx_staff_exceptions_staff ON staff_exceptions (staff_member_id);
CREATE INDEX IF NOT EXISTS idx_staff_exceptions_business ON staff_exceptions (business_id);
CREATE INDEX IF NOT EXISTS idx_staff_exceptions_date ON staff_exceptions (exception_date);

ALTER TABLE staff_exceptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON staff_exceptions FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 29. BOOKING_SERVICES — Services or class types offered
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_services (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id         BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name                TEXT NOT NULL,
  description         TEXT,
  duration_minutes    INTEGER NOT NULL CHECK (duration_minutes > 0),
  price               DECIMAL(10, 2) DEFAULT 0,
  currency            TEXT DEFAULT 'MXN' CHECK (currency IN ('MXN', 'USD', 'COP')),
  category            TEXT,
  max_capacity        INTEGER DEFAULT 1 CHECK (max_capacity > 0),
  requires_membership BOOLEAN DEFAULT FALSE,
  color               TEXT,
  is_active           BOOLEAN DEFAULT TRUE,
  sort_order          INTEGER DEFAULT 0,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_services_business ON booking_services (business_id);
CREATE INDEX IF NOT EXISTS idx_booking_services_active ON booking_services (business_id, is_active) WHERE is_active = TRUE;

ALTER TABLE booking_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON booking_services FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER booking_services_updated_at
  BEFORE UPDATE ON booking_services
  FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 30. BOOKING_SLOTS — Concrete bookable time windows
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_slots (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  service_id        UUID NOT NULL REFERENCES booking_services(id) ON DELETE CASCADE,
  staff_member_id   UUID REFERENCES staff_members(id) ON DELETE SET NULL,
  slot_type         TEXT NOT NULL CHECK (slot_type IN ('class', 'appointment')),
  slot_date         DATE NOT NULL,
  start_time        TIME NOT NULL,
  end_time          TIME NOT NULL,
  max_capacity      INTEGER DEFAULT 1 CHECK (max_capacity > 0),
  booked_count      INTEGER DEFAULT 0,
  status            TEXT DEFAULT 'available'
                      CHECK (status IN ('available', 'full', 'cancelled')),
  notes             TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_slots_business ON booking_slots (business_id);
CREATE INDEX IF NOT EXISTS idx_booking_slots_service ON booking_slots (service_id);
CREATE INDEX IF NOT EXISTS idx_booking_slots_staff ON booking_slots (staff_member_id);
CREATE INDEX IF NOT EXISTS idx_booking_slots_date ON booking_slots (business_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_booking_slots_available ON booking_slots (business_id, slot_date, status) WHERE status = 'available';

ALTER TABLE booking_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON booking_slots FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 31. BOOKING_CLIENTS — End-customers of the business
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_clients (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  phone             TEXT NOT NULL,
  name              TEXT,
  email             TEXT,
  notes             TEXT,
  is_active         BOOLEAN DEFAULT TRUE,
  otp_code          TEXT,
  otp_expires_at    TIMESTAMPTZ,
  total_bookings    INTEGER DEFAULT 0,
  last_booking_at   TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at   TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (business_id, phone)
);

CREATE INDEX IF NOT EXISTS idx_booking_clients_business ON booking_clients (business_id);
CREATE INDEX IF NOT EXISTS idx_booking_clients_phone ON booking_clients (business_id, phone);

ALTER TABLE booking_clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON booking_clients FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER booking_clients_updated_at
  BEFORE UPDATE ON booking_clients
  FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 32. BOOKINGS — Actual reservations
-- ============================================================================

CREATE TABLE IF NOT EXISTS bookings (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  slot_id           UUID NOT NULL REFERENCES booking_slots(id) ON DELETE CASCADE,
  client_id         UUID NOT NULL REFERENCES booking_clients(id) ON DELETE CASCADE,
  service_id        UUID NOT NULL REFERENCES booking_services(id) ON DELETE CASCADE,
  staff_member_id   UUID REFERENCES staff_members(id) ON DELETE SET NULL,
  status            TEXT DEFAULT 'confirmed'
                      CHECK (status IN ('confirmed', 'cancelled', 'completed', 'no_show')),
  booked_at         TIMESTAMPTZ DEFAULT NOW(),
  cancelled_at      TIMESTAMPTZ,
  cancellation_reason TEXT,
  admin_notes       TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (slot_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_bookings_business ON bookings (business_id);
CREATE INDEX IF NOT EXISTS idx_bookings_slot ON bookings (slot_id);
CREATE INDEX IF NOT EXISTS idx_bookings_client ON bookings (client_id);
CREATE INDEX IF NOT EXISTS idx_bookings_service ON bookings (service_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (business_id, status);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON bookings FOR ALL USING (true) WITH CHECK (true);


-- ============================================================================
-- 33. MEMBERSHIP_PLANS — For class-based model
-- ============================================================================

CREATE TABLE IF NOT EXISTS membership_plans (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id         BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name                TEXT NOT NULL,
  description         TEXT,
  classes_per_month   INTEGER,
  price               DECIMAL(10, 2) DEFAULT 0,
  currency            TEXT DEFAULT 'MXN' CHECK (currency IN ('MXN', 'USD', 'COP')),
  allowed_services    UUID[],
  is_active           BOOLEAN DEFAULT TRUE,
  sort_order          INTEGER DEFAULT 0,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_membership_plans_business ON membership_plans (business_id);
CREATE INDEX IF NOT EXISTS idx_membership_plans_active ON membership_plans (business_id, is_active) WHERE is_active = TRUE;

ALTER TABLE membership_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON membership_plans FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER membership_plans_updated_at
  BEFORE UPDATE ON membership_plans
  FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();


-- ============================================================================
-- 34. CLIENT_MEMBERSHIPS — Assigns a plan to a client
-- ============================================================================

CREATE TABLE IF NOT EXISTS client_memberships (
  id                UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id       BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  client_id         UUID NOT NULL REFERENCES booking_clients(id) ON DELETE CASCADE,
  plan_id           UUID NOT NULL REFERENCES membership_plans(id) ON DELETE CASCADE,
  status            TEXT DEFAULT 'active'
                      CHECK (status IN ('active', 'paused', 'cancelled', 'expired')),
  period_start      DATE NOT NULL,
  period_end        DATE NOT NULL,
  classes_used      INTEGER DEFAULT 0,
  classes_limit     INTEGER,
  admin_notes       TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  last_updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_client_memberships_business ON client_memberships (business_id);
CREATE INDEX IF NOT EXISTS idx_client_memberships_client ON client_memberships (client_id);
CREATE INDEX IF NOT EXISTS idx_client_memberships_plan ON client_memberships (plan_id);
CREATE INDEX IF NOT EXISTS idx_client_memberships_active ON client_memberships (business_id, status) WHERE status = 'active';

ALTER TABLE client_memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access" ON client_memberships FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER client_memberships_updated_at
  BEFORE UPDATE ON client_memberships
  FOR EACH ROW EXECUTE FUNCTION update_last_updated_at();
