-- Migration 008: Business contacts table + business codes + business notes
-- Adds random business_code to businesses, creates business_contacts table
-- for multiple contacts per business, and adds notes to businesses.

-- ── 1. Add business_code column to businesses ──
ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS business_code TEXT UNIQUE;

-- Generate codes for existing rows that don't have one
UPDATE businesses
SET business_code = 'BIZ-' || substr(md5(random()::text || id::text), 1, 6)
WHERE business_code IS NULL;

-- Make NOT NULL after backfill
ALTER TABLE businesses
  ALTER COLUMN business_code SET NOT NULL;

-- Set default for new rows
ALTER TABLE businesses
  ALTER COLUMN business_code SET DEFAULT 'BIZ-' || substr(md5(random()::text), 1, 6);

CREATE INDEX IF NOT EXISTS idx_businesses_code ON businesses (business_code);

-- ── 2. Add notes column to businesses ──
ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- ── 3. Create business_contacts table ──
CREATE TABLE IF NOT EXISTS business_contacts (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_code            TEXT UNIQUE NOT NULL DEFAULT 'CON-' || substr(md5(random()::text), 1, 6),
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,

  contact_name            TEXT,
  contact_title           TEXT,                -- role/position: owner, manager, cashier, employee, etc.
  contact_phone           TEXT,
  contact_email           TEXT,
  contact_whatsapp        TEXT,
  notes                   TEXT,                -- notes about this specific contact
  is_primary              BOOLEAN DEFAULT FALSE,

  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_business_contacts_business_id ON business_contacts (business_id);
CREATE INDEX IF NOT EXISTS idx_business_contacts_code ON business_contacts (contact_code);

-- ── 4. Migrate existing contact data from businesses to business_contacts ──
-- Creates a contact row for each business that has any contact_* field populated.
-- Marks these migrated contacts as primary.
INSERT INTO business_contacts (business_id, contact_name, contact_phone, contact_email, contact_whatsapp, is_primary)
SELECT id, contact_name, contact_phone, contact_email, contact_whatsapp, TRUE
FROM businesses
WHERE contact_name IS NOT NULL
   OR contact_phone IS NOT NULL
   OR contact_email IS NOT NULL
   OR contact_whatsapp IS NOT NULL;
