-- Migration 009: Analytics tracking tables
-- Creates analytics_events (raw tracking data) and analytics_summaries (daily rollups)

-- ── 1. Raw analytics events ──
CREATE TABLE IF NOT EXISTS analytics_events (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  website_id              UUID REFERENCES generated_websites(id) ON DELETE SET NULL,

  event_type              TEXT NOT NULL
                            CHECK (event_type IN (
                              'page_view',
                              'click_phone',
                              'click_email',
                              'click_directions',
                              'click_social',
                              'form_submit'
                            )),
  page_url                TEXT,
  referrer                TEXT,                -- domain only, not full URL
  device_type             TEXT
                            CHECK (device_type IN ('desktop', 'mobile', 'tablet')),
  visitor_id              TEXT,                -- hashed fingerprint for unique visitor counting (no PII)
  metadata                JSONB DEFAULT '{}',

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_analytics_events_business_id ON analytics_events (business_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_business_date ON analytics_events (business_id, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_type ON analytics_events (event_type);

-- ── 2. Daily analytics summaries (pre-aggregated) ──
CREATE TABLE IF NOT EXISTS analytics_summaries (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id             BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  date                    DATE NOT NULL,

  page_views              INTEGER DEFAULT 0,
  unique_visitors         INTEGER DEFAULT 0,
  phone_clicks            INTEGER DEFAULT 0,
  email_clicks            INTEGER DEFAULT 0,
  direction_clicks        INTEGER DEFAULT 0,
  social_clicks           INTEGER DEFAULT 0,
  form_submissions        INTEGER DEFAULT 0,

  top_referrers           JSONB DEFAULT '{}',  -- { "google.com": 15, "facebook.com": 8 }
  device_breakdown        JSONB DEFAULT '{}',  -- { "desktop": 60, "mobile": 35, "tablet": 5 }

  created_at              TIMESTAMPTZ DEFAULT NOW()
);

-- Unique constraint: one summary per business per day
CREATE UNIQUE INDEX IF NOT EXISTS idx_analytics_summaries_unique ON analytics_summaries (business_id, date);
CREATE INDEX IF NOT EXISTS idx_analytics_summaries_business_date ON analytics_summaries (business_id, date);
