-- ============================================================================
-- Migration 023: Admin website analytics metadata + access
-- ============================================================================
-- Keeps analytics first-party and privacy-conscious:
-- - coarse geo and attribution live in analytics_events.metadata
-- - direct browser reads are limited to employee admins
-- - service-role APIs continue to power customer-scoped and admin dashboards
-- ============================================================================

ALTER TABLE IF EXISTS public.analytics_events
  DROP CONSTRAINT IF EXISTS analytics_events_event_type_check;

ALTER TABLE IF EXISTS public.analytics_events
  ADD CONSTRAINT analytics_events_event_type_check
  CHECK (
    event_type IN (
      'page_view',
      'click_phone',
      'click_email',
      'click_directions',
      'click_social',
      'form_submit',
      'demo_view',
      'demo_leave'
    )
  );

COMMENT ON COLUMN public.analytics_events.metadata IS
  'Event metadata. Website events may include geo {city, region, country, continent, latitude, longitude, timezone} and attribution {utm_source, utm_medium, utm_campaign, utm_content, utm_term, gclid, fbclid, ttclid, msclkid}.';

CREATE TABLE IF NOT EXISTS public.excluded_ips (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address        TEXT NOT NULL UNIQUE,
  employee_id       UUID REFERENCES public.employees(id) ON DELETE SET NULL,
  label             TEXT,
  last_seen_at      TIMESTAMPTZ DEFAULT NOW(),
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_excluded_ips_address ON public.excluded_ips (ip_address);

ALTER TABLE IF EXISTS public.excluded_ips ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_employee_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.employees
    WHERE auth_user_id = auth.uid()
      AND is_active = true
      AND role = 'admin'
  );
$$;

DROP POLICY IF EXISTS "employee admin read analytics events" ON public.analytics_events;
CREATE POLICY "employee admin read analytics events"
  ON public.analytics_events
  FOR SELECT
  TO authenticated
  USING (public.is_employee_admin());

DROP POLICY IF EXISTS "employee admin read analytics summaries" ON public.analytics_summaries;
CREATE POLICY "employee admin read analytics summaries"
  ON public.analytics_summaries
  FOR SELECT
  TO authenticated
  USING (public.is_employee_admin());

DROP POLICY IF EXISTS "employee all access" ON public.excluded_ips;
CREATE POLICY "employee all access"
  ON public.excluded_ips
  FOR ALL
  TO authenticated
  USING (public.is_employee())
  WITH CHECK (public.is_employee());
